### ISSUE TITLE
Lengua de serpiente

### ISSUE THREAD

**Issue by PIC16f841** [council-of-rivendell/meccg-remaster#20]
El texto dice "contra cualquier personaje o servidor que tenga edoras como lugar natal" lo cual es confuso porque mezcla la parte con el todo. Propongo eliminar "o servidor" del texto (ver ice rules digest 34, query 1).Afecta tb a la versión en inglés

**Comment by council-of-rivendell** [comment]
No se puede cambiar el texto por un digest, Debe haber un CRF para poder cambiar el texto.
